INSERT INTO tag (id, nome) VALUES ('tag-1', 'Aventura') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-2', 'Ação') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-3', 'RPG') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-4', 'Puzzle') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-5', 'Estratégia') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-6', 'Simulação') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-7', 'Esportes') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-8', 'Corrida') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-9', 'Terror') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-10', 'Sobrevivência') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-11', 'Indie') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-12', 'Multiplayer') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-13', 'Singleplayer') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-14', 'Mundo Aberto') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-15', 'Pixel Art') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-16', '2D') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-17', '3D') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-18', 'Roguelike') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-19', 'Metroidvania') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-20', 'Plataforma') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-21', 'Fantasia') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-22', 'Ficção Científica') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-23', 'Medieval') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-24', 'Cyberpunk') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-25', 'Pós-Apocalíptico') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-26', 'Casual') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-27', 'Competitivo') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-28', 'História Rica') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-29', 'Exploração') ON CONFLICT (nome) DO NOTHING;
INSERT INTO tag (id, nome) VALUES ('tag-30', 'Crafting') ON CONFLICT (nome) DO NOTHING;
